openapi: 3.0.0
info:
  title: Engage 360 API
  description: Integration guide for tracking user events and identity mapping.
  version: 1.0.0
servers:
  - url: http://tracker.wigzopush.com/rest/v1
paths:
  /learn/identify:
    post:
      summary: Identify a user
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
        - in: query
          name: org_token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIdentify'
      responses:
        '200':
          description: Successful
  /learn/event:
    post:
      summary: Track an event
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
        - in: query
          name: org_token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Successful
components:
  schemas:
    UserIdentify:
      type: object
      required: [userId]
      properties:
        userId:
          type: string
        phone:
          type: string
        email:
          type: string
        customer_id:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
    Event:
      type: object
      required: [eventName, eventval, eventCategory, userId]
      properties:
        eventName:
          type: string
          enum: [product_view, order_completed, checkout_started, addtocart]
        eventval:
          type: object
          oneOf:
            - $ref: '#/components/schemas/ProductViewPayload'
            - $ref: '#/components/schemas/OrderCompletedPayload'
            - $ref: '#/components/schemas/CheckoutStartedPayload'
        eventCategory:
          type: string
        userId:
          type: string

    ProductViewPayload:
      type: object
      required: [canonicalUrl, productId, variants]
      properties:
        canonicalUrl:
          type: string
        tags:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: string
        productType:
          type: string
        vendor:
          type: string
        author:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        productId:
          type: string
        image:
          type: string
        category:
          type: string
        language:
          type: string
        variants:
          type: array
          items:
            type: object
            required: [variant_id, product_id, title, price]
            properties:
              variant_id:
                type: string
              product_id:
                type: string
              title:
                type: string
              sku:
                type: string
              image:
                type: string
              inventory_quantity:
                type: string
              price:
                type: string

    OrderCompletedPayload:
      type: object
      required: [orderId, customer_id, line_items]
      properties:
        orderId:
          type: string
        customer_id:
          type: string
        phone:
          type: string
        fullName:
          type: string
        email:
          type: string
        total_price:
          type: number
        total_line_items_price:
          type: number
        cart_token:
          type: string
        checkout_token:
          type: string
        ga_transaction_id:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        shipping_cost:
          type: number
        total_discounts:
          type: number
        city:
          type: string
        state:
          type: string
        country:
          type: string
        zip:
          type: string
        financial_status:
          type: string
        taxes_included:
          type: boolean
        coupons:
          type: array
          items:
            type: string
        line_items:
          type: array
          items:
            type: object
            required: [line_item_id, variant_id, product_id, quantity]
            properties:
              line_item_id:
                type: string
              variant_id:
                type: string
              product_id:
                type: string
              price:
                type: number
              quantity:
                type: integer
              product_discount:
                type: number
              fulfillment_status:
                type: string
              categories:
                type: string
              type:
                type: string

    CheckoutStartedPayload:
      type: object
      required: [line_items]
      properties:
        completed_at:
          type: string
        closed_at:
          type: string
        referring_site:
          type: string
        currency:
          type: string
        source_identifier:
          type: string
        total_discounts:
          type: string
        total_line_items_price:
          type: string
        total_price:
          type: string
        total_tax:
          type: string
        abandoned_checkout_url:
          type: string
        line_items:
          type: array
          items:
            type: object
            required: [checkout_id, product_id, quantity]
            properties:
              checkout_id:
                type: string
              product_id:
                type: string
              quantity:
                type: integer
              title:
                type: string
              variant_id:
                type: string
              variant_title:
                type: string
              variant_price:
                type: string
              vendor:
                type: string
              price:
                type: string
              taxable:
                type: boolean
