openapi: 3.0.0
info:
  title: Engage 360 API
  description: Integration guide for tracking user events and identity mapping.
  version: 1.0.0
servers:
  - url: http://tracker.wigzopush.com/rest/v1
paths:
  /learn/identify:
    post:
      summary: Identify a user
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
        - in: query
          name: org_token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIdentify'
      responses:
        '200':
          description: Successful
  /learn/event:
    post:
      summary: Track an event
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
        - in: query
          name: org_token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Successful
components:
  schemas:
    UserIdentify:
      type: object
      required: [userId]
      properties:
        userId:
          type: string
        phone:
          type: string
        email:
          type: string
        customer_id:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
    Event:
      type: object
      required: [eventName, eventval, eventCategory, userId]
      properties:
        eventName:
          type: string
        eventval:
          type: object
        eventCategory:
          type: string
        userId:
          type: string
